# Generated by Django 5.2.6 on 2025-09-23 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedmodel',
            old_name='file',
            new_name='model_file',
        ),
        migrations.RemoveField(
            model_name='uploadedmodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='uploadedmodel',
            name='notes',
        ),
    ]
